# SPDX-FileCopyrightText: Â© 2024 Matt Williams <matt.williams@bristol.ac.uk>
# SPDX-License-Identifier: MIT
---
apiVersion: v2
name: conch
version: "0.0.0"  # Set by release script
appVersion: ""  # Set by release script
sources:
  - https://github.com/isambard-sc/conch/
