# SPDX-FileCopyrightText: Â© 2024 Matt Williams <matt.williams@bristol.ac.uk>
# SPDX-License-Identifier: MIT
---
config: {}
image:
  registry: ghcr.io/isambard-sc
  name: conch
  tag:  # defaults to appVersion if not set
port: 3000
signing_key_dir: "/signing_key"
log_level: info
replicas:
